"""#################################################################################################
count all the base paired bases in a multi-ct file generated by RNAstructure:stochastic
each ct block begins with sequence_length, input fasta file name
   74  tRNA.1F7U.fa
and the data row are six columns, e.g.
    a b       c    d    e    f
    3 C       2    4    0    3
    4 U       3    5    0    4
    5 C       4    6   22    5
    6 G       5    7   21    6

a   base position
b   base
c   previous base position
d   following base position
e   paired base position
f   base position

5 March 2026    michael gribskov
#################################################################################################"""
from collections import defaultdict
import matplotlib.pyplot as plt
from matplotlib.patches import Arc
import math

def read_ct(filename):
    """---------------------------------------------------------------------------------------------
    read ct structures

    :return: list   base positions, each is a dict showing bases that can pair with that position
    ---------------------------------------------------------------------------------------------"""

    ct = open(ctfile, 'r')

    first = True
    pairs = defaultdict(lambda: defaultdict(int))
    for line in ct:
        field = line.strip().split()

        if len(field) < 6:
            # title line
            seqlen = int(field[0])
            id = field[1]

            # if first:
            #     pairs = [[] for _ in range(seqlen)]
            #     first = False

            continue

        else:
            base0 = field[0]
            base1 = field[4]

        # if base0 < base1:
            # only count pairs in low to high order, conver to zero based
            pairs[base0][base1] += 1

    # convert to counts
    # arc = []
    # for pos in pairs:

    return pairs, seqlen

def arc_plot(p1, p2, center, radius, ax, lw):
    """---------------------------------------------------------------------------------------------
    Plots an arc between two points using a known center and radius in Matplotlib.

    # Example usage:
    point1 = (1, 0)
    point2 = (0, 1)
    center = (0, 0)
    radius = 1

    :param p1:int   point1
    :param p2:int   point2
    :param center:int   center
    :param radius:int   radius
    :return:
    ---------------------------------------------------------------------------------------------"""
    # Calculate angles of the two points relative to the center
    angle1 = math.degrees(math.atan2(p1[1] - center[1], p1[0] - center[0]))
    angle2 = math.degrees(math.atan2(p2[1] - center[1], p2[0] - center[0]))
    if angle2 < angle1:
        angle1, angle2 = angle2, angle1

    # Create the arc patch
    arc = plt.matplotlib.patches.Arc(center, 3*radius, 2*radius, angle=0,
                                     theta1=angle1, theta2=angle2, color='green',
                                     linewidth=lw, antialiased=True)

    ax.add_patch(arc)

    # Plot the points
    # ax.scatter([p1[0], p2[0]], [p1[1], p2[1]], color='red')
    # ax.set_xlim(center[0] - radius * 1.5, center[0] + radius * 1.5)
    # ax.set_ylim(center[1] - radius * 1.5, center[1] + radius * 1.5)
    # ax.set_aspect('equal', adjustable='box')
    return

if __name__ == '__main__':
    ctfile = '../../work/2602_test_install/testmanager/mtest_260305bugfix/stochastic/tRNA.1F7U.ct'
    ctfile = '../../work/2602_test_install/testmanager/mtest_260305bugfix/stochastic/rnasep_a2.Nitrosomonas_europaea.ct'
    # ctfile = '../../work/2602_test_install/testmanager/mtest_260305bugfix/stochastic/5S_a.Halorubrum_saccharovorum.ct'

    structure, size = read_ct(ctfile)
    arc = []
    for s in sorted(structure, key=lambda s: int(s)):
        for pairedbase in structure[s]:
            print(f'{s}\t{pairedbase}\t{structure[s][pairedbase]}')
            arc.append({'left':s, 'right':pairedbase, 'weight':structure[s][pairedbase]})

    # plt.figure()
    fig, ax = plt.subplots(figsize=(14, 8))
    # ax.set_aspect('equal')
    for a in arc:
        x0 = (int(a['left'])/size/2,0.25)
        x1 = (int(a['right'])/size/2,0.25)
        weight = int(a['weight'])/500
        center = ((x0[0] + x1[0]) / 2.0,0.25)
        radius = center[0]/2
        arc_plot(x0, x1, center, radius, ax, weight)

    plt.show()
    exit(0)
